name: kubernetes-worker
base: core18
version: "0.0.1"
summary: A complete Kubernetes worker
description: |
  A fully functional Kubernetes worker in a snap.  This includes kubelet,
  kubectl, containerd and ctr.

grade: devel
confinement: strict

plugs:
  docker-privileged:
    interface: docker-support
    privileged-containers: true
  k8s-kubelet:
    flavor: kubelet
    interface: kubernetes-support
  dot-kube:
    interface: personal-files
    write:
      - $HOME/.kube

hooks:
  configure:
    plugs:
      - dot-kube
  remove:
    plugs:
      - network-control
      - k8s-kubelet
      - kernel-module-control

layout:
  /opt/containerd:
    bind: $SNAP_COMMON/containerd/opt
  /var/lib/containerd:
    bind: $SNAP_COMMON/containerd/var/lib
  /opt/cni/bin:
    bind: $SNAP_DATA/cni/bin
  /sbin/ipset:
    bind: $SNAP/bin/ipset
  /usr/local/bin:
    bind: $SNAP/bin
  /var/lib/cni:
    bind: $SNAP_DATA/cni
  /var/lib/kubelet:
    bind: $SNAP_COMMON/kubelet
  /var/lib/kube-proxy:
    bind: $SNAP_DATA/kube-proxy
  /var/lib/kube-proxy-config:
    bind: $SNAP_DATA/kube-proxy-config
  /etc/cni/net.d:
    bind: $SNAP_DATA/cni/net.d
  /var/log:
    bind: $SNAP_DATA/log

apps:
  containerd:
    command: containerd.wrapper
    daemon: simple
    plugs:
      - docker-privileged
      - docker-support
      - kubernetes-support
      - firewall-control
      - kernel-module-control
      - network-bind
      - network-control
      - mount-observe
      - network-setup-control
  kubelet:
    command: kubelet.wrapper
    daemon: simple
    plugs:
      - docker-privileged
      - docker-support
      - kubernetes-support
      - dot-kube
      - firewall-control
      - hardware-observe
      - k8s-kubelet
      - mount-observe
      - network-bind
      - network-control
      - process-control
      - system-observe
      - network-setup-control
  ctr:
    command: ctr.wrapper
    plugs:
      - docker-privileged
      - docker-support
      - firewall-control
      - network-bind
      - network-control
  kubectl:
    command: kubectl.wrapper
    plugs:
      - dot-kube
      - firewall-control
      - hardware-observe
      - home
      - k8s-kubelet
      - mount-observe
      - network-bind
      - network-control
      - process-control
      - system-observe

parts:
  setup:
    after:
      - artifacts
      - wrappers
    source: build/
    plugin: dump
  patches:
    plugin: dump
    source: patches/
    # don't stage any of the patches into the snap
    prime: ["-*"]
  wrappers:
    source: wrappers/
    plugin: dump
    organize:
      containerd.wrapper: bin/containerd.wrapper
      ctr.wrapper: bin/ctr.wrapper
      kubectl.wrapper: bin/kubectl.wrapper
      kubelet.wrapper: bin/kubelet.wrapper
  artifacts:
    source: artifacts/
    plugin: dump
  runc:
    after:
      - setup
      - patches
    plugin: nil
    build-snaps:
      - go/1.12/stable
    build-packages:
      - git
      - gcc
      - make
      - pkg-config
      - btrfs-tools
      - libseccomp-dev
    override-build: |
      set -eu
      . ../../../parts/setup/build/common.sh
      . ../../../parts/setup/build/lock.sh

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin

      go get github.com/opencontainers/runc
      (
        cd $GOPATH/src/github.com/opencontainers/runc
        git checkout ${RUNC_COMMIT}
        git reset --hard HEAD
        # patch runc to never do prctl to drop new privs label for all containers
        for patch in "$SNAPCRAFT_STAGE"/runc-patches/*.patch; do
          echo "Applying $(basename "$patch") ..."
          git apply --ignore-space-change --ignore-whitespace "$patch"
          echo
        done

        make BUILDTAGS='seccomp apparmor'
      )
      cp $GOPATH/src/github.com/opencontainers/runc/runc $SNAPCRAFT_PART_INSTALL/bin/
    organize:
      go/src/github.com/opencontainers/runc/runc: bin/runc
      containerd/install/bin/*: bin/
    stage-packages:
      - systemd
      - libnss-myhostname
      - libnss-resolve
      - libnss-mymachines
      - conntrack
      - aufs-tools
      - gawk
      - sed
      - socat
      - grep
      - libssl1.0.0
      - coreutils
      - hostname
      - diffutils
    stage:
      - -sbin/xtables-multi
      - -sbin/iptables*
      - -lib/xtables
  containerd:
    after:
      - setup
      - runc
    plugin: nil
    build-snaps:
      - go/1.12/stable
    build-packages:
      - git
      - gcc
      - make
      - pkg-config
      - btrfs-tools
      - libseccomp-dev
    override-build: |
      set -eu
      . ../../../parts/setup/build/common.sh
      . ../../../parts/setup/build/lock.sh

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin

      go get github.com/containerd/containerd
      (
        cd $GOPATH/src/github.com/containerd/containerd
        git checkout ${CONTAINERD_COMMIT}
        make
      )
      cp $GOPATH/src/github.com/containerd/containerd/bin/* $SNAPCRAFT_PART_INSTALL/bin/
      rm $SNAPCRAFT_PART_INSTALL/bin/containerd-stress
    organize:
      go/src/github.com/containerd/containerd/bin/*: bin/
      containerd/install/bin/*: bin/
    stage-packages:
      - systemd
      - libnss-myhostname
      - libnss-resolve
      - libnss-mymachines
      - conntrack
      - aufs-tools
      - gawk
      - sed
      - socat
      - grep
      - libssl1.0.0
      - coreutils
      - hostname
      - diffutils
    stage:
      - -sbin/xtables-multi
      - -sbin/iptables*
      - -lib/xtables
  kubernetes:
    after:
      - setup
      - runc
      - containerd
    plugin: nil
    build-snaps:
      - go/1.12/stable
    build-packages:
      - git
      - gcc
      - make
      - rsync
      - pkg-config
    stage-packages:
      - conntrack
      - ipset
    override-build: |
      set -eu
      . ../../../parts/setup/build/common.sh
      . ../../../parts/setup/build/lock.sh

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin

      go get -d k8s.io/kubernetes || true
      (
        cd $GOPATH/src/k8s.io/kubernetes
        git checkout ${KUBERNETES_COMMIT}
        make all WHAT="cmd/kubelet cmd/kubectl cmd/kube-proxy"
      )
      cp $GOPATH/src/k8s.io/kubernetes/_output/local/go/bin/* $SNAPCRAFT_PART_INSTALL/bin/
  cni-plugins:
    after:
      - kubernetes
    plugin: nil
    build-snaps:
      - go/1.12/stable
    build-packages:
      - git
      - gcc
      - make
      - pkg-config
    override-build: |
      set -eu
      . ../../../parts/setup/build/common.sh
      . ../../../parts/setup/build/lock.sh

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/cni

      go get -d github.com/containernetworking/plugins || true
      (
        cd $GOPATH/src/github.com/containernetworking/plugins
        git checkout ${CNI_PLUGINS_COMMIT}
        ./build_linux.sh
      )
      cp $GOPATH/src/github.com/containernetworking/plugins/bin/* $SNAPCRAFT_PART_INSTALL/bin/cni/
  aws-cli:
    after:
      - cni-plugins
    plugin: python
    python-version: python3
    python-packages:
      - awscli
    build-packages:
      - python-pip
      - libcurl4-openssl-dev
  aws-iam-authenticator:
    after:
      - aws-cli
    plugin: nil
    build-packages:
      - curl
    override-build: |
      set -eu
      . ../../../parts/setup/build/common.sh
      . ../../../parts/setup/build/lock.sh

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin

      curl -o aws-iam-authenticator \
        https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
      chmod +x aws-iam-authenticator
      cp aws-iam-authenticator $SNAPCRAFT_PART_INSTALL/bin/
