name: CI

on: [push]

jobs:
  build:
    name: Create snap package
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Install lxd
      run: sudo snap install lxd
    - name: Migrate lxd
      run: sudo /snap/bin/lxd.migrate -yes
    - name: Wait for lxd to be ready
      run: sudo /snap/bin/lxd waitready
    - name: Initialise lxd
      run: sudo /snap/bin/lxd init --auto
    - name: Install snapcraft
      run: sudo snap install snapcraft --classic
    - name: Build snap
      run: sudo snapcraft build --use-lxd
    - name: Make built snap name generic
      run: sudo mv kubernetes-worker*.snap kubernetes-worker.snap
    - name: Uploading artifact
      uses: actions/upload-artifact@v1
      with:
        name: kubernetes-worker.snap
        path: kubernetes-worker.snap
