name: CI

on: [push]

jobs:
  build:
    name: Create Snap Package
    runs-on: ubuntu-latest

    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        use_lxd: true
    - name: Build Snap
      run: snapcraft build --use-lxd
      
