apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
networkPlugin: cni
rootDir: ${SNAP_COMMON}/kubelet/
certDir: ${SNAP_COMMON}/certs/
containerRuntime: remote
containerRuntimeEndpoint: ${SNAP_COMMON}/containerd/run/containerd.sock
authentication:
  x509:
    clientCAFile: ${SNAP_COMMON}/certs/ca.crt
